// Generated by jextract

package com.voipfuture.jminesweep.client.nativelinux;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor cfgetospeed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cfgetospeed$MH = RuntimeHelper.downcallHandle(
        "cfgetospeed",
        constants$0.cfgetospeed$FUNC
    );
    static final FunctionDescriptor cfgetispeed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cfgetispeed$MH = RuntimeHelper.downcallHandle(
        "cfgetispeed",
        constants$0.cfgetispeed$FUNC
    );
    static final FunctionDescriptor cfsetospeed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle cfsetospeed$MH = RuntimeHelper.downcallHandle(
        "cfsetospeed",
        constants$0.cfsetospeed$FUNC
    );
    static final FunctionDescriptor cfsetispeed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle cfsetispeed$MH = RuntimeHelper.downcallHandle(
        "cfsetispeed",
        constants$0.cfsetispeed$FUNC
    );
    static final FunctionDescriptor cfsetspeed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle cfsetspeed$MH = RuntimeHelper.downcallHandle(
        "cfsetspeed",
        constants$0.cfsetspeed$FUNC
    );
    static final FunctionDescriptor tcgetattr$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle tcgetattr$MH = RuntimeHelper.downcallHandle(
        "tcgetattr",
        constants$0.tcgetattr$FUNC
    );
}


