// Generated by jextract

package com.voipfuture.jminesweep.client.nativelinux;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final FunctionDescriptor tcgetsid$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle tcgetsid$MH = RuntimeHelper.downcallHandle(
        "tcgetsid",
        constants$2.tcgetsid$FUNC
    );
}


