// Generated by jextract

package com.voipfuture.jminesweep.client.nativelinux;

import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.OfAddress;
import static java.lang.foreign.ValueLayout.OfByte;
import static java.lang.foreign.ValueLayout.OfDouble;
import static java.lang.foreign.ValueLayout.OfFloat;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;
import static java.lang.foreign.ValueLayout.OfShort;
public class termios_h  {

    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * #define _TERMIOS_H 1
     * }
     */
    public static int _TERMIOS_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _FEATURES_H 1
     * }
     */
    public static int _FEATURES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DEFAULT_SOURCE 1
     * }
     */
    public static int _DEFAULT_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_ISOC2X 0
     * }
     */
    public static int __GLIBC_USE_ISOC2X() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC11 1
     * }
     */
    public static int __USE_ISOC11() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC99 1
     * }
     */
    public static int __USE_ISOC99() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC95 1
     * }
     */
    public static int __USE_ISOC95() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX_IMPLICITLY 1
     * }
     */
    public static int __USE_POSIX_IMPLICITLY() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SOURCE 1
     * }
     */
    public static int _POSIX_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX 1
     * }
     */
    public static int __USE_POSIX() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX2 1
     * }
     */
    public static int __USE_POSIX2() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX199309 1
     * }
     */
    public static int __USE_POSIX199309() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX199506 1
     * }
     */
    public static int __USE_POSIX199506() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_XOPEN2K 1
     * }
     */
    public static int __USE_XOPEN2K() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_XOPEN2K8 1
     * }
     */
    public static int __USE_XOPEN2K8() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _ATFILE_SOURCE 1
     * }
     */
    public static int _ATFILE_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __WORDSIZE 64
     * }
     */
    public static int __WORDSIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __WORDSIZE_TIME64_COMPAT32 1
     * }
     */
    public static int __WORDSIZE_TIME64_COMPAT32() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __SYSCALL_WORDSIZE 64
     * }
     */
    public static int __SYSCALL_WORDSIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __USE_MISC 1
     * }
     */
    public static int __USE_MISC() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ATFILE 1
     * }
     */
    public static int __USE_ATFILE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_FORTIFY_LEVEL 0
     * }
     */
    public static int __USE_FORTIFY_LEVEL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_DEPRECATED_GETS 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_GETS() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_DEPRECATED_SCANF 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_SCANF() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _STDC_PREDEF_H 1
     * }
     */
    public static int _STDC_PREDEF_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_559__ 1
     * }
     */
    public static int __STDC_IEC_559__() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_559_COMPLEX__ 1
     * }
     */
    public static int __STDC_IEC_559_COMPLEX__() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __GNU_LIBRARY__ 6
     * }
     */
    public static int __GNU_LIBRARY__() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define __GLIBC__ 2
     * }
     */
    public static int __GLIBC__() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_MINOR__ 35
     * }
     */
    public static int __GLIBC_MINOR__() {
        return (int)35L;
    }
    /**
     * {@snippet :
     * #define _SYS_CDEFS_H 1
     * }
     */
    public static int _SYS_CDEFS_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __glibc_c99_flexarr_available 1
     * }
     */
    public static int __glibc_c99_flexarr_available() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI 0
     * }
     */
    public static int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __HAVE_GENERIC_SELECTION 1
     * }
     */
    public static int __HAVE_GENERIC_SELECTION() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_TYPES_H 1
     * }
     */
    public static int _BITS_TYPES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_TYPESIZES_H 1
     * }
     */
    public static int _BITS_TYPESIZES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __OFF_T_MATCHES_OFF64_T 1
     * }
     */
    public static int __OFF_T_MATCHES_OFF64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __INO_T_MATCHES_INO64_T 1
     * }
     */
    public static int __INO_T_MATCHES_INO64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __RLIM_T_MATCHES_RLIM64_T 1
     * }
     */
    public static int __RLIM_T_MATCHES_RLIM64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STATFS_MATCHES_STATFS64 1
     * }
     */
    public static int __STATFS_MATCHES_STATFS64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 1
     * }
     */
    public static int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __FD_SETSIZE 1024
     * }
     */
    public static int __FD_SETSIZE() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define _BITS_TIME64_H 1
     * }
     */
    public static int _BITS_TIME64_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define NCCS 32
     * }
     */
    public static int NCCS() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define _HAVE_STRUCT_TERMIOS_C_ISPEED 1
     * }
     */
    public static int _HAVE_STRUCT_TERMIOS_C_ISPEED() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _HAVE_STRUCT_TERMIOS_C_OSPEED 1
     * }
     */
    public static int _HAVE_STRUCT_TERMIOS_C_OSPEED() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define VINTR 0
     * }
     */
    public static int VINTR() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define VQUIT 1
     * }
     */
    public static int VQUIT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define VERASE 2
     * }
     */
    public static int VERASE() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define VKILL 3
     * }
     */
    public static int VKILL() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define VEOF 4
     * }
     */
    public static int VEOF() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define VTIME 5
     * }
     */
    public static int VTIME() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * #define VMIN 6
     * }
     */
    public static int VMIN() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define VSWTC 7
     * }
     */
    public static int VSWTC() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * #define VSTART 8
     * }
     */
    public static int VSTART() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define VSTOP 9
     * }
     */
    public static int VSTOP() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * #define VSUSP 10
     * }
     */
    public static int VSUSP() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * #define VEOL 11
     * }
     */
    public static int VEOL() {
        return (int)11L;
    }
    /**
     * {@snippet :
     * #define VREPRINT 12
     * }
     */
    public static int VREPRINT() {
        return (int)12L;
    }
    /**
     * {@snippet :
     * #define VDISCARD 13
     * }
     */
    public static int VDISCARD() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * #define VWERASE 14
     * }
     */
    public static int VWERASE() {
        return (int)14L;
    }
    /**
     * {@snippet :
     * #define VLNEXT 15
     * }
     */
    public static int VLNEXT() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * #define VEOL2 16
     * }
     */
    public static int VEOL2() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define IGNBRK 1
     * }
     */
    public static int IGNBRK() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define BRKINT 2
     * }
     */
    public static int BRKINT() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define IGNPAR 4
     * }
     */
    public static int IGNPAR() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define PARMRK 8
     * }
     */
    public static int PARMRK() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define INPCK 16
     * }
     */
    public static int INPCK() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define ISTRIP 32
     * }
     */
    public static int ISTRIP() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define INLCR 64
     * }
     */
    public static int INLCR() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define IGNCR 128
     * }
     */
    public static int IGNCR() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define ICRNL 256
     * }
     */
    public static int ICRNL() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define IUCLC 512
     * }
     */
    public static int IUCLC() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define IXON 1024
     * }
     */
    public static int IXON() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define IXANY 2048
     * }
     */
    public static int IXANY() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define IXOFF 4096
     * }
     */
    public static int IXOFF() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define IMAXBEL 8192
     * }
     */
    public static int IMAXBEL() {
        return (int)8192L;
    }
    /**
     * {@snippet :
     * #define IUTF8 16384
     * }
     */
    public static int IUTF8() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define OPOST 1
     * }
     */
    public static int OPOST() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define OLCUC 2
     * }
     */
    public static int OLCUC() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ONLCR 4
     * }
     */
    public static int ONLCR() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define OCRNL 8
     * }
     */
    public static int OCRNL() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define ONOCR 16
     * }
     */
    public static int ONOCR() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define ONLRET 32
     * }
     */
    public static int ONLRET() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define OFILL 64
     * }
     */
    public static int OFILL() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define OFDEL 128
     * }
     */
    public static int OFDEL() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define NLDLY 256
     * }
     */
    public static int NLDLY() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define NL0 0
     * }
     */
    public static int NL0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define NL1 256
     * }
     */
    public static int NL1() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define CRDLY 1536
     * }
     */
    public static int CRDLY() {
        return (int)1536L;
    }
    /**
     * {@snippet :
     * #define CR0 0
     * }
     */
    public static int CR0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define CR1 512
     * }
     */
    public static int CR1() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define CR2 1024
     * }
     */
    public static int CR2() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define CR3 1536
     * }
     */
    public static int CR3() {
        return (int)1536L;
    }
    /**
     * {@snippet :
     * #define TABDLY 6144
     * }
     */
    public static int TABDLY() {
        return (int)6144L;
    }
    /**
     * {@snippet :
     * #define TAB0 0
     * }
     */
    public static int TAB0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define TAB1 2048
     * }
     */
    public static int TAB1() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define TAB2 4096
     * }
     */
    public static int TAB2() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define TAB3 6144
     * }
     */
    public static int TAB3() {
        return (int)6144L;
    }
    /**
     * {@snippet :
     * #define BSDLY 8192
     * }
     */
    public static int BSDLY() {
        return (int)8192L;
    }
    /**
     * {@snippet :
     * #define BS0 0
     * }
     */
    public static int BS0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define BS1 8192
     * }
     */
    public static int BS1() {
        return (int)8192L;
    }
    /**
     * {@snippet :
     * #define FFDLY 32768
     * }
     */
    public static int FFDLY() {
        return (int)32768L;
    }
    /**
     * {@snippet :
     * #define FF0 0
     * }
     */
    public static int FF0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define FF1 32768
     * }
     */
    public static int FF1() {
        return (int)32768L;
    }
    /**
     * {@snippet :
     * #define VTDLY 16384
     * }
     */
    public static int VTDLY() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define VT0 0
     * }
     */
    public static int VT0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define VT1 16384
     * }
     */
    public static int VT1() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define XTABS 6144
     * }
     */
    public static int XTABS() {
        return (int)6144L;
    }
    /**
     * {@snippet :
     * #define B0 0
     * }
     */
    public static int B0() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define B50 1
     * }
     */
    public static int B50() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define B75 2
     * }
     */
    public static int B75() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define B110 3
     * }
     */
    public static int B110() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define B134 4
     * }
     */
    public static int B134() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define B150 5
     * }
     */
    public static int B150() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * #define B200 6
     * }
     */
    public static int B200() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define B300 7
     * }
     */
    public static int B300() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * #define B600 8
     * }
     */
    public static int B600() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define B1200 9
     * }
     */
    public static int B1200() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * #define B1800 10
     * }
     */
    public static int B1800() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * #define B2400 11
     * }
     */
    public static int B2400() {
        return (int)11L;
    }
    /**
     * {@snippet :
     * #define B4800 12
     * }
     */
    public static int B4800() {
        return (int)12L;
    }
    /**
     * {@snippet :
     * #define B9600 13
     * }
     */
    public static int B9600() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * #define B19200 14
     * }
     */
    public static int B19200() {
        return (int)14L;
    }
    /**
     * {@snippet :
     * #define B38400 15
     * }
     */
    public static int B38400() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * #define CBAUD 4111
     * }
     */
    public static int CBAUD() {
        return (int)4111L;
    }
    /**
     * {@snippet :
     * #define CBAUDEX 4096
     * }
     */
    public static int CBAUDEX() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define CIBAUD 269418496
     * }
     */
    public static int CIBAUD() {
        return (int)269418496L;
    }
    /**
     * {@snippet :
     * #define CMSPAR 1073741824
     * }
     */
    public static int CMSPAR() {
        return (int)1073741824L;
    }
    /**
     * {@snippet :
     * #define B57600 4097
     * }
     */
    public static int B57600() {
        return (int)4097L;
    }
    /**
     * {@snippet :
     * #define B115200 4098
     * }
     */
    public static int B115200() {
        return (int)4098L;
    }
    /**
     * {@snippet :
     * #define B230400 4099
     * }
     */
    public static int B230400() {
        return (int)4099L;
    }
    /**
     * {@snippet :
     * #define B460800 4100
     * }
     */
    public static int B460800() {
        return (int)4100L;
    }
    /**
     * {@snippet :
     * #define B500000 4101
     * }
     */
    public static int B500000() {
        return (int)4101L;
    }
    /**
     * {@snippet :
     * #define B576000 4102
     * }
     */
    public static int B576000() {
        return (int)4102L;
    }
    /**
     * {@snippet :
     * #define B921600 4103
     * }
     */
    public static int B921600() {
        return (int)4103L;
    }
    /**
     * {@snippet :
     * #define B1000000 4104
     * }
     */
    public static int B1000000() {
        return (int)4104L;
    }
    /**
     * {@snippet :
     * #define B1152000 4105
     * }
     */
    public static int B1152000() {
        return (int)4105L;
    }
    /**
     * {@snippet :
     * #define B1500000 4106
     * }
     */
    public static int B1500000() {
        return (int)4106L;
    }
    /**
     * {@snippet :
     * #define B2000000 4107
     * }
     */
    public static int B2000000() {
        return (int)4107L;
    }
    /**
     * {@snippet :
     * #define B2500000 4108
     * }
     */
    public static int B2500000() {
        return (int)4108L;
    }
    /**
     * {@snippet :
     * #define B3000000 4109
     * }
     */
    public static int B3000000() {
        return (int)4109L;
    }
    /**
     * {@snippet :
     * #define B3500000 4110
     * }
     */
    public static int B3500000() {
        return (int)4110L;
    }
    /**
     * {@snippet :
     * #define B4000000 4111
     * }
     */
    public static int B4000000() {
        return (int)4111L;
    }
    /**
     * {@snippet :
     * #define CSIZE 48
     * }
     */
    public static int CSIZE() {
        return (int)48L;
    }
    /**
     * {@snippet :
     * #define CS5 0
     * }
     */
    public static int CS5() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define CS6 16
     * }
     */
    public static int CS6() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define CS7 32
     * }
     */
    public static int CS7() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define CS8 48
     * }
     */
    public static int CS8() {
        return (int)48L;
    }
    /**
     * {@snippet :
     * #define CSTOPB 64
     * }
     */
    public static int CSTOPB() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define CREAD 128
     * }
     */
    public static int CREAD() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define PARENB 256
     * }
     */
    public static int PARENB() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define PARODD 512
     * }
     */
    public static int PARODD() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define HUPCL 1024
     * }
     */
    public static int HUPCL() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define CLOCAL 2048
     * }
     */
    public static int CLOCAL() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define ISIG 1
     * }
     */
    public static int ISIG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ICANON 2
     * }
     */
    public static int ICANON() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define XCASE 4
     * }
     */
    public static int XCASE() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define ECHO 8
     * }
     */
    public static int ECHO() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define ECHOE 16
     * }
     */
    public static int ECHOE() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define ECHOK 32
     * }
     */
    public static int ECHOK() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define ECHONL 64
     * }
     */
    public static int ECHONL() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define NOFLSH 128
     * }
     */
    public static int NOFLSH() {
        return (int)128L;
    }
    /**
     * {@snippet :
     * #define TOSTOP 256
     * }
     */
    public static int TOSTOP() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * #define ECHOCTL 512
     * }
     */
    public static int ECHOCTL() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * #define ECHOPRT 1024
     * }
     */
    public static int ECHOPRT() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define ECHOKE 2048
     * }
     */
    public static int ECHOKE() {
        return (int)2048L;
    }
    /**
     * {@snippet :
     * #define FLUSHO 4096
     * }
     */
    public static int FLUSHO() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * #define PENDIN 16384
     * }
     */
    public static int PENDIN() {
        return (int)16384L;
    }
    /**
     * {@snippet :
     * #define IEXTEN 32768
     * }
     */
    public static int IEXTEN() {
        return (int)32768L;
    }
    /**
     * {@snippet :
     * #define EXTPROC 65536
     * }
     */
    public static int EXTPROC() {
        return (int)65536L;
    }
    /**
     * {@snippet :
     * #define TIOCSER_TEMT 1
     * }
     */
    public static int TIOCSER_TEMT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define TCOOFF 0
     * }
     */
    public static int TCOOFF() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define TCOON 1
     * }
     */
    public static int TCOON() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define TCIOFF 2
     * }
     */
    public static int TCIOFF() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define TCION 3
     * }
     */
    public static int TCION() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define TCIFLUSH 0
     * }
     */
    public static int TCIFLUSH() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define TCOFLUSH 1
     * }
     */
    public static int TCOFLUSH() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define TCIOFLUSH 2
     * }
     */
    public static int TCIOFLUSH() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define TCSANOW 0
     * }
     */
    public static int TCSANOW() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define TCSADRAIN 1
     * }
     */
    public static int TCSADRAIN() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define TCSAFLUSH 2
     * }
     */
    public static int TCSAFLUSH() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define CERASE 127
     * }
     */
    public static int CERASE() {
        return (int)127L;
    }
    /**
     * {@snippet :
     * #define CMIN 1
     * }
     */
    public static int CMIN() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define CQUIT 28
     * }
     */
    public static int CQUIT() {
        return (int)28L;
    }
    /**
     * {@snippet :
     * #define CTIME 0
     * }
     */
    public static int CTIME() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * typedef unsigned char __u_char;
     * }
     */
    public static final OfByte __u_char = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned short __u_short;
     * }
     */
    public static final OfShort __u_short = Constants$root.C_SHORT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __u_int;
     * }
     */
    public static final OfInt __u_int = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __u_long;
     * }
     */
    public static final OfLong __u_long = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef signed char __int8_t;
     * }
     */
    public static final OfByte __int8_t = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned char __uint8_t;
     * }
     */
    public static final OfByte __uint8_t = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef short __int16_t;
     * }
     */
    public static final OfShort __int16_t = Constants$root.C_SHORT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned short __uint16_t;
     * }
     */
    public static final OfShort __uint16_t = Constants$root.C_SHORT$LAYOUT;
    /**
     * {@snippet :
     * typedef int __int32_t;
     * }
     */
    public static final OfInt __int32_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __uint32_t;
     * }
     */
    public static final OfInt __uint32_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long __int64_t;
     * }
     */
    public static final OfLong __int64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __uint64_t;
     * }
     */
    public static final OfLong __uint64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef signed char __int_least8_t;
     * }
     */
    public static final OfByte __int_least8_t = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned char __uint_least8_t;
     * }
     */
    public static final OfByte __uint_least8_t = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef short __int_least16_t;
     * }
     */
    public static final OfShort __int_least16_t = Constants$root.C_SHORT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned short __uint_least16_t;
     * }
     */
    public static final OfShort __uint_least16_t = Constants$root.C_SHORT$LAYOUT;
    /**
     * {@snippet :
     * typedef int __int_least32_t;
     * }
     */
    public static final OfInt __int_least32_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __uint_least32_t;
     * }
     */
    public static final OfInt __uint_least32_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long __int_least64_t;
     * }
     */
    public static final OfLong __int_least64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __uint_least64_t;
     * }
     */
    public static final OfLong __uint_least64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __quad_t;
     * }
     */
    public static final OfLong __quad_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __u_quad_t;
     * }
     */
    public static final OfLong __u_quad_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __intmax_t;
     * }
     */
    public static final OfLong __intmax_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __uintmax_t;
     * }
     */
    public static final OfLong __uintmax_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __dev_t;
     * }
     */
    public static final OfLong __dev_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __uid_t;
     * }
     */
    public static final OfInt __uid_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __gid_t;
     * }
     */
    public static final OfInt __gid_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __ino_t;
     * }
     */
    public static final OfLong __ino_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __ino64_t;
     * }
     */
    public static final OfLong __ino64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __mode_t;
     * }
     */
    public static final OfInt __mode_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __nlink_t;
     * }
     */
    public static final OfLong __nlink_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __off_t;
     * }
     */
    public static final OfLong __off_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __off64_t;
     * }
     */
    public static final OfLong __off64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef int __pid_t;
     * }
     */
    public static final OfInt __pid_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long __clock_t;
     * }
     */
    public static final OfLong __clock_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __rlim_t;
     * }
     */
    public static final OfLong __rlim_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __rlim64_t;
     * }
     */
    public static final OfLong __rlim64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __id_t;
     * }
     */
    public static final OfInt __id_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long __time_t;
     * }
     */
    public static final OfLong __time_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __useconds_t;
     * }
     */
    public static final OfInt __useconds_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long __suseconds_t;
     * }
     */
    public static final OfLong __suseconds_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __suseconds64_t;
     * }
     */
    public static final OfLong __suseconds64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef int __daddr_t;
     * }
     */
    public static final OfInt __daddr_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef int __key_t;
     * }
     */
    public static final OfInt __key_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef int __clockid_t;
     * }
     */
    public static final OfInt __clockid_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef void* __timer_t;
     * }
     */
    public static final OfAddress __timer_t = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * typedef long __blksize_t;
     * }
     */
    public static final OfLong __blksize_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __blkcnt_t;
     * }
     */
    public static final OfLong __blkcnt_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __blkcnt64_t;
     * }
     */
    public static final OfLong __blkcnt64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __fsblkcnt_t;
     * }
     */
    public static final OfLong __fsblkcnt_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __fsblkcnt64_t;
     * }
     */
    public static final OfLong __fsblkcnt64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __fsfilcnt_t;
     * }
     */
    public static final OfLong __fsfilcnt_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __fsfilcnt64_t;
     * }
     */
    public static final OfLong __fsfilcnt64_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __fsword_t;
     * }
     */
    public static final OfLong __fsword_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __ssize_t;
     * }
     */
    public static final OfLong __ssize_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __syscall_slong_t;
     * }
     */
    public static final OfLong __syscall_slong_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned long __syscall_ulong_t;
     * }
     */
    public static final OfLong __syscall_ulong_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef long __loff_t;
     * }
     */
    public static final OfLong __loff_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef char* __caddr_t;
     * }
     */
    public static final OfAddress __caddr_t = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * typedef long __intptr_t;
     * }
     */
    public static final OfLong __intptr_t = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int __socklen_t;
     * }
     */
    public static final OfInt __socklen_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef int __sig_atomic_t;
     * }
     */
    public static final OfInt __sig_atomic_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef int pid_t;
     * }
     */
    public static final OfInt pid_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned char cc_t;
     * }
     */
    public static final OfByte cc_t = Constants$root.C_CHAR$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int speed_t;
     * }
     */
    public static final OfInt speed_t = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef unsigned int tcflag_t;
     * }
     */
    public static final OfInt tcflag_t = Constants$root.C_INT$LAYOUT;
    public static MethodHandle cfgetospeed$MH() {
        return RuntimeHelper.requireNonNull(constants$0.cfgetospeed$MH,"cfgetospeed");
    }
    /**
     * {@snippet :
     * speed_t cfgetospeed(struct termios* __termios_p);
     * }
     */
    public static int cfgetospeed(MemorySegment __termios_p) {
        var mh$ = cfgetospeed$MH();
        try {
            return (int)mh$.invokeExact(__termios_p);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle cfgetispeed$MH() {
        return RuntimeHelper.requireNonNull(constants$0.cfgetispeed$MH,"cfgetispeed");
    }
    /**
     * {@snippet :
     * speed_t cfgetispeed(struct termios* __termios_p);
     * }
     */
    public static int cfgetispeed(MemorySegment __termios_p) {
        var mh$ = cfgetispeed$MH();
        try {
            return (int)mh$.invokeExact(__termios_p);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle cfsetospeed$MH() {
        return RuntimeHelper.requireNonNull(constants$0.cfsetospeed$MH,"cfsetospeed");
    }
    /**
     * {@snippet :
     * int cfsetospeed(struct termios* __termios_p, speed_t __speed);
     * }
     */
    public static int cfsetospeed(MemorySegment __termios_p, int __speed) {
        var mh$ = cfsetospeed$MH();
        try {
            return (int)mh$.invokeExact(__termios_p, __speed);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle cfsetispeed$MH() {
        return RuntimeHelper.requireNonNull(constants$0.cfsetispeed$MH,"cfsetispeed");
    }
    /**
     * {@snippet :
     * int cfsetispeed(struct termios* __termios_p, speed_t __speed);
     * }
     */
    public static int cfsetispeed(MemorySegment __termios_p, int __speed) {
        var mh$ = cfsetispeed$MH();
        try {
            return (int)mh$.invokeExact(__termios_p, __speed);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle cfsetspeed$MH() {
        return RuntimeHelper.requireNonNull(constants$0.cfsetspeed$MH,"cfsetspeed");
    }
    /**
     * {@snippet :
     * int cfsetspeed(struct termios* __termios_p, speed_t __speed);
     * }O
     */
    public static int cfsetspeed(MemorySegment __termios_p, int __speed) {
        var mh$ = cfsetspeed$MH();
        try {
            return (int)mh$.invokeExact(__termios_p, __speed);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcgetattr$MH() {
        return RuntimeHelper.requireNonNull(constants$0.tcgetattr$MH,"tcgetattr");
    }
    /**
     * {@snippet :
     * int tcgetattr(int __fd, struct termios* __termios_p);
     * }
     */
    public static int tcgetattr(int __fd, MemorySegment __termios_p) {
        var mh$ = tcgetattr$MH();
        try {
            return (int)mh$.invokeExact(__fd, __termios_p);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcsetattr$MH() {
        return RuntimeHelper.requireNonNull(constants$1.tcsetattr$MH,"tcsetattr");
    }
    /**
     * {@snippet :
     * int tcsetattr(int __fd, int __optional_actions, struct termios* __termios_p);
     * }
     */
    public static int tcsetattr(int __fd, int __optional_actions, MemorySegment __termios_p) {
        var mh$ = tcsetattr$MH();
        try {
            return (int)mh$.invokeExact(__fd, __optional_actions, __termios_p);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle cfmakeraw$MH() {
        return RuntimeHelper.requireNonNull(constants$1.cfmakeraw$MH,"cfmakeraw");
    }
    /**
     * {@snippet :
     * void cfmakeraw(struct termios* __termios_p);
     * }
     */
    public static void cfmakeraw(MemorySegment __termios_p) {
        var mh$ = cfmakeraw$MH();
        try {
            mh$.invokeExact(__termios_p);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcsendbreak$MH() {
        return RuntimeHelper.requireNonNull(constants$1.tcsendbreak$MH,"tcsendbreak");
    }
    /**
     * {@snippet :
     * int tcsendbreak(int __fd, int __duration);
     * }*/
    public static int tcsendbreak(int __fd, int __duration) {
        var mh$ = tcsendbreak$MH();
        try {
            return (int)mh$.invokeExact(__fd, __duration);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcdrain$MH() {
        return RuntimeHelper.requireNonNull(constants$1.tcdrain$MH,"tcdrain");
    }
    /**
     * {@snippet :
     * int tcdrain(int __fd);
     * }
     */
    public static int tcdrain(int __fd) {
        var mh$ = tcdrain$MH();
        try {
            return (int)mh$.invokeExact(__fd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcflush$MH() {
        return RuntimeHelper.requireNonNull(constants$1.tcflush$MH,"tcflush");
    }
    /**
     * {@snippet :
     * int tcflush(int __fd, int __queue_selector);
     * }
     */
    public static int tcflush(int __fd, int __queue_selector) {
        var mh$ = tcflush$MH();
        try {
            return (int)mh$.invokeExact(__fd, __queue_selector);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcflow$MH() {
        return RuntimeHelper.requireNonNull(constants$1.tcflow$MH,"tcflow");
    }
    /**
     * {@snippet :
     * int tcflow(int __fd, int __action);
     * }
     */
    public static int tcflow(int __fd, int __action) {
        var mh$ = tcflow$MH();
        try {
            return (int)mh$.invokeExact(__fd, __action);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle tcgetsid$MH() {
        return RuntimeHelper.requireNonNull(constants$2.tcgetsid$MH,"tcgetsid");
    }
    /**
     * {@snippet :
     * __pid_t tcgetsid(int __fd);
     * }
     */
    public static int tcgetsid(int __fd) {
        var mh$ = tcgetsid$MH();
        try {
            return (int)mh$.invokeExact(__fd);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * #define _POSIX_C_SOURCE 200809
     * }
     */
    public static long _POSIX_C_SOURCE() {
        return 200809L;
    }
    /**
     * {@snippet :
     * #define __TIMESIZE 64
     * }
     */
    public static int __TIMESIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_60559_BFP__ 201404
     * }
     */
    public static long __STDC_IEC_60559_BFP__() {
        return 201404L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_60559_COMPLEX__ 201404
     * }
     */
    public static long __STDC_IEC_60559_COMPLEX__() {
        return 201404L;
    }
    /**
     * {@snippet :
     * #define __STDC_ISO_10646__ 201706
     * }
     */
    public static long __STDC_ISO_10646__() {
        return 201706L;
    }
    /**
     * {@snippet :
     * #define EXTA 14
     * }
     */
    public static int EXTA() {
        return (int)14L;
    }
    /**
     * {@snippet :
     * #define EXTB 15
     * }
     */
    public static int EXTB() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * #define CRTSCTS 2147483648
     * }
     */
    public static int CRTSCTS() {
        return (int)2147483648L;
    }
    /**
     * {@snippet :
     * #define __MAX_BAUD 4111
     * }
     */
    public static int __MAX_BAUD() {
        return (int)4111L;
    }
    /**
     * {@snippet :
     * #define TTYDEF_IFLAG 11554
     * }
     */
    public static int TTYDEF_IFLAG() {
        return (int)11554L;
    }
    /**
     * {@snippet :
     * #define TTYDEF_OFLAG 6149
     * }
     */
    public static int TTYDEF_OFLAG() {
        return (int)6149L;
    }
    /**
     * {@snippet :
     * #define TTYDEF_LFLAG 35355
     * }
     */
    public static int TTYDEF_LFLAG() {
        return (int)35355L;
    }
    /**
     * {@snippet :
     * #define TTYDEF_CFLAG 1440
     * }
     */
    public static int TTYDEF_CFLAG() {
        return (int)1440L;
    }
    /**
     * {@snippet :
     * #define TTYDEF_SPEED 13
     * }
     */
    public static int TTYDEF_SPEED() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * #define CEOF 4
     * }
     */
    public static int CEOF() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define CEOL 0
     * }
     */
    public static int CEOL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define CINTR 3
     * }
     */
    public static int CINTR() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define CSTATUS 0
     * }
     */
    public static int CSTATUS() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define CKILL 21
     * }
     */
    public static int CKILL() {
        return (int)21L;
    }
    /**
     * {@snippet :
     * #define CSUSP 26
     * }
     */
    public static int CSUSP() {
        return (int)26L;
    }
    /**
     * {@snippet :
     * #define CDSUSP 25
     * }
     */
    public static int CDSUSP() {
        return (int)25L;
    }
    /**
     * {@snippet :
     * #define CSTART 17
     * }
     */
    public static int CSTART() {
        return (int)17L;
    }
    /**
     * {@snippet :
     * #define CSTOP 19
     * }
     */
    public static int CSTOP() {
        return (int)19L;
    }
    /**
     * {@snippet :
     * #define CLNEXT 22
     * }
     */
    public static int CLNEXT() {
        return (int)22L;
    }
    /**
     * {@snippet :
     * #define CDISCARD 15
     * }
     */
    public static int CDISCARD() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * #define CWERASE 23
     * }
     */
    public static int CWERASE() {
        return (int)23L;
    }
    /**
     * {@snippet :
     * #define CREPRINT 18
     * }
     */
    public static int CREPRINT() {
        return (int)18L;
    }
    /**
     * {@snippet :
     * #define CEOT 4
     * }
     */
    public static int CEOT() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define CBRK 0
     * }
     */
    public static int CBRK() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define CRPRNT 18
     * }
     */
    public static int CRPRNT() {
        return (int)18L;
    }
    /**
     * {@snippet :
     * #define CFLUSH 15
     * }
     */
    public static int CFLUSH() {
        return (int)15L;
    }
}